import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { motion, AnimatePresence } from "framer-motion";
import { CheckCircle2, Download, Share2, Shield, Home, Loader2, Copy, Mail, Twitter, Linkedin, Facebook } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";
import { toast } from "sonner";

export default function VerificationResult() {
  const [, setLocation] = useLocation();
  const [isDownloading, setIsDownloading] = useState(false);
  const [showShareMenu, setShowShareMenu] = useState(false);

  // Mock verification result
  const result = {
    verificationCode: "VER-2024-06-10-001",
    trustScore: 98,
    status: "verified",
    documentType: "Passport",
    faceMatch: 99.2,
    fraudDetection: "No fraud detected",
    timestamp: new Date().toLocaleString(),
    qrCode: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=TRUSTLINK-VERIFICATION-12345",
  };

  const handleDownloadReport = async () => {
    try {
      setIsDownloading(true);
      
      // Create report content
      const reportContent = `
TRUSTLINK VERIFICATION REPORT
========================================

Verification Code: ${result.verificationCode}
Timestamp: ${result.timestamp}

VERIFICATION RESULTS
========================================
Status: ${result.status.toUpperCase()}
Trust Score: ${result.trustScore}%
Document Type: ${result.documentType}
Face Match Accuracy: ${result.faceMatch}%
Fraud Detection: ${result.fraudDetection}

VALIDITY
========================================
Valid For: 365 Days
Expiry Date: ${new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toLocaleDateString()}

This verification report confirms that the identity has been successfully verified
through TrustLink's advanced verification system including OCR extraction, 
biometric face matching, and fraud detection.

Generated by TrustLink - Smart Digital Identity Verification System
      `;

      // Create blob and download
      const blob = new Blob([reportContent], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `trustlink-report-${result.verificationCode}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast.success("Report downloaded successfully!");
    } catch (error) {
      console.error("Download failed:", error);
      toast.error("Failed to download report");
    } finally {
      setIsDownloading(false);
    }
  };

  const verificationLink = `${window.location.origin}/verify/lookup?code=${result.verificationCode}`;

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(verificationLink);
      toast.success("Verification link copied to clipboard!");
      setShowShareMenu(false);
    } catch (error) {
      toast.error("Failed to copy link");
    }
  };

  const handleShareTwitter = () => {
    const text = `I just completed my identity verification on TrustLink! Trust Score: ${result.trustScore}% 🎉`;
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(verificationLink)}`;
    window.open(url, "_blank", "width=550,height=420");
    setShowShareMenu(false);
    toast.success("Opening Twitter...");
  };

  const handleShareLinkedIn = () => {
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(verificationLink)}`;
    window.open(url, "_blank", "width=550,height=420");
    setShowShareMenu(false);
    toast.success("Opening LinkedIn...");
  };

  const handleShareFacebook = () => {
    const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(verificationLink)}`;
    window.open(url, "_blank", "width=550,height=420");
    setShowShareMenu(false);
    toast.success("Opening Facebook...");
  };

  const handleShareEmail = () => {
    const subject = "My TrustLink Verification";
    const body = `Check out my verified identity on TrustLink!\n\nVerification Code: ${result.verificationCode}\nTrust Score: ${result.trustScore}%\nStatus: ${result.status}\n\nVerify here: ${verificationLink}`;
    const url = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = url;
    setShowShareMenu(false);
  };

  const handleBackHome = () => {
    setLocation('/');
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.6 },
    },
  };

  const shareMenuVariants = {
    hidden: { opacity: 0, scale: 0.8, y: -10 },
    visible: {
      opacity: 1,
      scale: 1,
      y: 0,
      transition: { duration: 0.3 },
    },
    exit: {
      opacity: 0,
      scale: 0.8,
      y: -10,
      transition: { duration: 0.2 },
    },
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
      {/* Animated Background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <motion.div
          className="absolute top-0 right-1/3 w-96 h-96 bg-gradient-to-r from-green-600 to-emerald-600 rounded-full blur-3xl opacity-20"
          animate={{
            x: [0, 100, 0],
            y: [0, 50, 0],
            scale: [1, 1.3, 1],
          }}
          transition={{ duration: 8, repeat: Infinity }}
        />
        <motion.div
          className="absolute bottom-0 left-1/4 w-96 h-96 bg-gradient-to-r from-yellow-600 to-orange-600 rounded-full blur-3xl opacity-20"
          animate={{
            x: [0, -100, 0],
            y: [0, 100, 0],
            scale: [1.2, 1, 1.2],
          }}
          transition={{ duration: 10, repeat: Infinity }}
        />
      </div>

      {/* Navigation */}
      <nav className="fixed top-0 w-full z-50 bg-slate-950/80 backdrop-blur-xl border-b border-slate-800">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <motion.div
            className="flex items-center gap-2"
            animate={{ rotate: 360 }}
            transition={{ duration: 20, repeat: Infinity }}
          >
            <div className="w-10 h-10 bg-gradient-to-br from-green-500 via-emerald-500 to-teal-500 rounded-lg flex items-center justify-center">
              <Shield className="w-6 h-6 text-white" />
            </div>
            <span className="text-xl font-bold bg-gradient-to-r from-green-400 via-emerald-400 to-teal-400 bg-clip-text text-transparent">
              TrustLink
            </span>
          </motion.div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="pt-24 pb-12 relative z-10">
        <div className="container mx-auto px-4 max-w-3xl">
          {/* Success Animation */}
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
          >
            <motion.div
              className="mb-6 flex justify-center"
              animate={{ scale: [1, 1.2, 1], rotate: [0, 5, -5, 0] }}
              transition={{ duration: 0.8, repeat: Infinity }}
            >
              <div className="w-24 h-24 bg-gradient-to-br from-green-500 to-emerald-500 rounded-full flex items-center justify-center shadow-2xl shadow-green-500/50">
                <CheckCircle2 className="w-16 h-16 text-white" />
              </div>
            </motion.div>
            <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-green-400 to-emerald-400 bg-clip-text text-transparent">
              Verification Complete! 🎉
            </h1>
            <p className="text-xl text-slate-300">
              Your identity has been successfully verified
            </p>
          </motion.div>

          {/* Trust Score Card */}
          <motion.div
            className="mb-8"
            variants={itemVariants}
            initial="hidden"
            animate="visible"
          >
            <motion.div className="group relative">
              <div className="absolute inset-0 bg-gradient-to-r from-green-600 to-emerald-600 rounded-2xl blur-xl opacity-0 group-hover:opacity-50 transition-opacity duration-300" />
              <Card className="relative p-8 border-0 bg-gradient-to-br from-green-50 to-emerald-50 backdrop-blur-sm">
                <div className="text-center mb-8">
                  <motion.div
                    className="text-7xl font-bold mb-4"
                    animate={{ scale: [1, 1.05, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    <span className="bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">
                      {result.trustScore}%
                    </span>
                  </motion.div>
                  <p className="text-2xl font-semibold text-slate-800">Trust Score</p>
                </div>

                {/* Details Grid */}
                <div className="grid md:grid-cols-3 gap-6">
                  <motion.div
                    className="text-center"
                    animate={{ y: [0, -5, 0] }}
                    transition={{ duration: 2, repeat: Infinity, delay: 0 }}
                  >
                    <p className="text-slate-600 text-sm mb-2">Document Type</p>
                    <p className="text-lg font-semibold text-slate-800">{result.documentType}</p>
                  </motion.div>
                  <motion.div
                    className="text-center"
                    animate={{ y: [0, -5, 0] }}
                    transition={{ duration: 2, repeat: Infinity, delay: 0.2 }}
                  >
                    <p className="text-slate-600 text-sm mb-2">Face Match</p>
                    <p className="text-lg font-semibold text-green-600">{result.faceMatch}%</p>
                  </motion.div>
                  <motion.div
                    className="text-center"
                    animate={{ y: [0, -5, 0] }}
                    transition={{ duration: 2, repeat: Infinity, delay: 0.4 }}
                  >
                    <p className="text-slate-600 text-sm mb-2">Fraud Detection</p>
                    <p className="text-lg font-semibold text-green-600">✓ Clear</p>
                  </motion.div>
                </div>
              </Card>
            </motion.div>
          </motion.div>

          {/* QR Code */}
          <motion.div
            className="mb-8"
            variants={itemVariants}
            initial="hidden"
            animate="visible"
          >
            <motion.div className="group relative">
              <div className="absolute inset-0 bg-gradient-to-r from-yellow-600 to-orange-600 rounded-2xl blur-xl opacity-0 group-hover:opacity-50 transition-opacity duration-300" />
              <Card className="relative p-8 border-0 bg-gradient-to-br from-yellow-50 to-orange-50 backdrop-blur-sm">
                <h2 className="text-2xl font-bold mb-6 bg-gradient-to-r from-yellow-600 to-orange-600 bg-clip-text text-transparent">
                  Your Verification QR Code
                </h2>
                <div className="flex flex-col items-center gap-6">
                  <motion.div
                    className="p-6 bg-white border-2 border-yellow-300 rounded-lg shadow-lg"
                    animate={{ scale: [1, 1.05, 1], rotate: [0, 2, -2, 0] }}
                    transition={{ duration: 3, repeat: Infinity }}
                  >
                    <img
                      src={result.qrCode}
                      alt="Verification QR Code"
                      className="w-64 h-64"
                    />
                  </motion.div>
                  <p className="text-center text-slate-700 max-w-md">
                    Share this QR code to prove your identity. Anyone can scan it to verify your status.
                  </p>
                  <div className="relative">
                    <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                      <Button
                        onClick={() => setShowShareMenu(!showShareMenu)}
                        className="bg-gradient-to-r from-yellow-600 to-orange-600 text-white hover:shadow-2xl hover:shadow-orange-500/50 px-8 py-6"
                      >
                        <Share2 className="mr-2 w-5 h-5" />
                        Share Verification
                      </Button>
                    </motion.div>

                    {/* Share Menu */}
                    <AnimatePresence>
                      {showShareMenu && (
                        <motion.div
                          className="absolute top-full mt-3 left-1/2 transform -translate-x-1/2 bg-slate-900 border border-slate-700 rounded-xl shadow-2xl p-4 min-w-max z-50"
                          variants={shareMenuVariants}
                          initial="hidden"
                          animate="visible"
                          exit="exit"
                        >
                          <div className="space-y-2">
                            {/* Copy Link */}
                            <motion.button
                              onClick={handleCopyLink}
                              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors text-white text-left"
                              whileHover={{ x: 5 }}
                            >
                              <Copy className="w-5 h-5 text-cyan-400" />
                              <div>
                                <p className="font-semibold">Copy Link</p>
                                <p className="text-xs text-slate-400">Copy to clipboard</p>
                              </div>
                            </motion.button>

                            {/* Email Share */}
                            <motion.button
                              onClick={handleShareEmail}
                              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors text-white text-left"
                              whileHover={{ x: 5 }}
                            >
                              <Mail className="w-5 h-5 text-red-400" />
                              <div>
                                <p className="font-semibold">Email</p>
                                <p className="text-xs text-slate-400">Share via email</p>
                              </div>
                            </motion.button>

                            {/* Twitter Share */}
                            <motion.button
                              onClick={handleShareTwitter}
                              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors text-white text-left"
                              whileHover={{ x: 5 }}
                            >
                              <Twitter className="w-5 h-5 text-blue-400" />
                              <div>
                                <p className="font-semibold">Twitter</p>
                                <p className="text-xs text-slate-400">Share on Twitter</p>
                              </div>
                            </motion.button>

                            {/* LinkedIn Share */}
                            <motion.button
                              onClick={handleShareLinkedIn}
                              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors text-white text-left"
                              whileHover={{ x: 5 }}
                            >
                              <Linkedin className="w-5 h-5 text-blue-600" />
                              <div>
                                <p className="font-semibold">LinkedIn</p>
                                <p className="text-xs text-slate-400">Share on LinkedIn</p>
                              </div>
                            </motion.button>

                            {/* Facebook Share */}
                            <motion.button
                              onClick={handleShareFacebook}
                              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors text-white text-left"
                              whileHover={{ x: 5 }}
                            >
                              <Facebook className="w-5 h-5 text-blue-500" />
                              <div>
                                <p className="font-semibold">Facebook</p>
                                <p className="text-xs text-slate-400">Share on Facebook</p>
                              </div>
                            </motion.button>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              </Card>
            </motion.div>
          </motion.div>

          {/* Verification Details */}
          <motion.div
            className="mb-8"
            variants={itemVariants}
            initial="hidden"
            animate="visible"
          >
            <motion.div className="group relative">
              <div className="absolute inset-0 bg-gradient-to-r from-cyan-600 to-blue-600 rounded-2xl blur-xl opacity-0 group-hover:opacity-50 transition-opacity duration-300" />
              <Card className="relative p-8 border-0 bg-gradient-to-br from-cyan-50 to-blue-50 backdrop-blur-sm">
                <h2 className="text-2xl font-bold mb-6 bg-gradient-to-r from-cyan-600 to-blue-600 bg-clip-text text-transparent">
                  Verification Details
                </h2>
                <div className="space-y-4">
                  <motion.div
                    className="flex justify-between items-center pb-4 border-b border-cyan-200"
                    animate={{ x: [0, 5, 0] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    <span className="text-slate-600">Verification ID</span>
                    <span className="font-semibold text-slate-800">{result.verificationCode}</span>
                  </motion.div>
                  <motion.div
                    className="flex justify-between items-center pb-4 border-b border-cyan-200"
                    animate={{ x: [0, 5, 0] }}
                    transition={{ duration: 2, repeat: Infinity, delay: 0.1 }}
                  >
                    <span className="text-slate-600">Timestamp</span>
                    <span className="font-semibold text-slate-800">{result.timestamp}</span>
                  </motion.div>
                  <motion.div
                    className="flex justify-between items-center pb-4 border-b border-cyan-200"
                    animate={{ x: [0, 5, 0] }}
                    transition={{ duration: 2, repeat: Infinity, delay: 0.2 }}
                  >
                    <span className="text-slate-600">Status</span>
                    <span className="font-semibold text-green-600">✓ Verified</span>
                  </motion.div>
                  <motion.div
                    className="flex justify-between items-center"
                    animate={{ x: [0, 5, 0] }}
                    transition={{ duration: 2, repeat: Infinity, delay: 0.3 }}
                  >
                    <span className="text-slate-600">Validity</span>
                    <span className="font-semibold text-slate-800">365 Days</span>
                  </motion.div>
                </div>
              </Card>
            </motion.div>
          </motion.div>

          {/* Actions */}
          <motion.div
            className="flex gap-4 justify-center flex-wrap"
            variants={itemVariants}
            initial="hidden"
            animate="visible"
          >
            <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
              <Button
                onClick={handleDownloadReport}
                disabled={isDownloading}
                className="bg-gradient-to-r from-green-600 to-emerald-600 text-white hover:shadow-2xl hover:shadow-green-500/50 px-8 py-6 disabled:opacity-50"
              >
                {isDownloading ? (
                  <>
                    <Loader2 className="mr-2 w-5 h-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Download className="mr-2 w-5 h-5" />
                    Download Report
                  </>
                )}
              </Button>
            </motion.div>
            <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
              <Button
                onClick={handleBackHome}
                variant="outline"
                className="border-cyan-500 text-cyan-300 hover:bg-cyan-500/10 px-8 py-6"
              >
                <Home className="mr-2 w-5 h-5" />
                Back to Home
              </Button>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
